spring.application.name=voyage-backend
server.port=8081

spring.profiles.active=local

spring.datasource.url=${DB_URL:}
spring.datasource.username=${DB_USERNAME:}
spring.datasource.password=${DB_PASSWORD:}

spring.datasource.driver-class-name=oracle.jdbc.OracleDriver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.OracleDialect

# ===============================
# JWT CONFIG
# ===============================
app.jwt.secret=${JWT_SECRET:VoyageVietSecretKeyForJwtAuthenticationMustBeAtLeast32Bytes}
app.jwt.access-token-expiration-ms=86400000

# ===============================
# LOCAL SEED CONFIG
# ===============================
app.seed.admin.enabled=true
app.seed.admin.email=admin@voyageviet.local
app.seed.admin.password=Admin@123456

app.seed.super-admin.email=superadmin@voyageviet.local
app.seed.super-admin.password=SuperAdmin@123456

# ===============================
# SAMPLE DATA SEED CONFIG
# ===============================
app.seed.sample.enabled=true

# ===============================
# CLOUDINARY CONFIG
# ===============================
cloudinary.cloud-name=${CLOUDINARY_CLOUD_NAME:}
cloudinary.api-key=${CLOUDINARY_API_KEY:}
cloudinary.api-secret=${CLOUDINARY_API_SECRET:}
cloudinary.folder=${CLOUDINARY_FOLDER:voyage-viet}