package com.voyageviet.backend.audit.entity;

public enum AuditAction {
    USER_STATUS_UPDATED,
    USER_ROLE_UPDATED,
    BOOKING_STATUS_UPDATED,
    FEATURE_FLAG_UPDATED,
    FEATURE_TOGGLE,

    TOUR_CREATED,
    TOUR_UPDATED,
    TOUR_PUBLISHED,
    TOUR_ARCHIVED,
    TOUR_DUPLICATED,
    TOUR_DELETED,

    BOOKING_CREATED,
    BOOKING_CONFIRMED,
    BOOKING_CANCELLED,
    BOOKING_COMPLETED,

    PAYMENT_REFUNDED,

    PROMOTION_CREATED,
    PROMOTION_UPDATED,
    PROMOTION_STATUS_UPDATED,
    PROMOTION_DELETED,

    REVIEW_APPROVED,
    REVIEW_REJECTED,

    MEDIA_UPLOADED,
    MEDIA_DELETED
}
